CXX = g++
INCLUDES= -I./
CXXFLAGS = -g $(INCLUDES)
SRCM= NodeFunctions.cpp
OBJM = $(SRCM:.cpp=.o)
LINKFLAGS= -lcppunit

tesnode: TestNode.cpp NodeFunctions.cpp $(OBJM)
	$(CXX) $(CXXFLAGS) -o $@ TestNode.cpp $(OBJM) $(LINKFLAGS) $(LINKFLAGSLOG4) $(LIBLOG)

# Default compile

.cpp.o:
	$(CXX) $(CXXFLAGS) -c $< -o $@
